version: "3.3"
  
services:
  nginx:
    image: "nginx"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/server.conf
      - ./static_cdn/:/static_cdn/
      - ./media/:/media/
    ports:
      - "8888:8777"
    depends_on:
      - web
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_gallery
      - POSTGRES_USER=django_gallery_user
      - POSTGRES_PASSWORD=django_gallery_password
  web:
    build: .
    restart: on-failure
    environment:
      - DEBUG=False
      - DATABASE_URL=psql://django_gallery_user:django_gallery_password@db/django_gallery
    command: 
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic --no-input
        gunicorn django_gallery.wsgi:application --bind 0.0.0.0:8000  --workers 3 --reload
    volumes:
      # - .:/code
      # - ./static_cdn/:/code/static_cdn/
      - ./media/:/code/media/
    # ports:
    #   - "8000:8000" # Ports are disabled because it is handled by nginx
    depends_on:
      - db
  
volumes:
  pgdata: